rootProject.name = "Mind-map"

include(":androidApp")
include(":desktopApp")
include(":shared")
include(":modules-app:navigation")
include(":modules-app:data")
include(":modules-app:domain")
include(":modules-app:core")
include(":modules-app:features:map")
include(":modules-app:features:map:common")
include(":modules-app:features:catalog")
include(":modules-app:features:catalog:common")
include(":modules-app:features:login")
include(":modules-app:features:login:common")
include(":modules-app:features:details")
include(":modules-app:features:details:common")
include(":modules-app:features:testing")
include(":modules-app:features:testing:common")
